---
pagetitle: CSS Units - Step 3
example:
  title: CSS Units - Step 3
  instructions: |-
    Then modify the CSS rules so that a few elements use relative units: `em`, `rem`, `vw`, `vh`, `vmin`, `vmax`. 
    
    What do each of these units represent?

    How do the font sizes of elements higher in the HTML tree affect the font size of their children?
  runtime: repl
  mode:
    document: html
  initial:
    js: ~
    css: |-
      html {
        /* font-size: 16px; */
      }
      .outer {
        font-size: 16px;
      }
      .inner {
      }
      .outer p {
      }
      .inner p {
      }
      .paragraph-two {
        /* why doesn't this do anything? */
      }
      .outer h2 {
      }
      .outer .inner h2 {}
  solution:
    js: ~
    css: |-
      html {
        font-size: 16px;
      }
      .outer {
        font-size: 16px;
      }
      .inner {
        font-size: 1em;
      }
      .outer p {
        font-size: 100%;
      }
      .inner p {
        font-size: 25px;
        font-size: 1.5em;
      }
      .paragraph-two {
        /* why doesn't this do anything? */
        /* hint: add element or class to selector */
        /* try: p.paragraph-two */
        /* try: move this rule up */
        font-size: 2em;
      }
      .outer h2 {
        font-size: 28px;
        /*color: blue;*/
      }
      .outer .inner h2 {
        /* change .outer font-size */
        font-size: 1.66em;
      }
output: js4shiny::html_document_js4shiny

---
<div><!--for pandoc-->
<div class="outer">

  <h1>Lorem Title</h1>

  <div class="inner">

    <h2>Section One</h2>

    <p class="paragraph-one">
      Ipsum hendrerit natoque ultricies vitae egestas cras condimentum quis.
      Condimentum semper cursus venenatis sodales quis magnis commodo posuere!
      Nisl inceptos quis nunc arcu nostra quam eros dui posuere dictumst mus conubia ad netus!
    </p>

    <p class="paragraph-two">
      Dolor fringilla dis penatibus consequat montes in maecenas pharetra et donec.
      Nascetur purus justo rutrum ultricies sollicitudin ac bibendum phasellus cubilia vestibulum!
      Metus turpis mattis hac sodales leo laoreet.
      Nascetur erat integer volutpat sapien venenatis himenaeos ridiculus nascetur arcu pretium.
    </p>

  </div>

  <h2>Section Two</h2>

  <p class="paragraph-three">
    Sit sollicitudin fusce torquent vivamus donec scelerisque odio etiam arcu facilisi non cum velit massa!
    <span class="p-three-sentence">Fermentum gravida integer auctor molestie quis dignissim tincidunt gravida!</span>
    Tellus quis tempor habitasse curae sem integer tellus tempor pulvinar?
    In natoque suscipit ultrices etiam ridiculus eu etiam commodo enim porta neque.
    A a quisque montes habitant tristique habitant!
  </p>
</div>
</div><!--for pandoc-->
