---
pagetitle: CSS Units - Inheritance
example:
  title: CSS Units - Inheritance
  instructions: |2-

    I've set the font color of the `.outer` `<div>` to be red. Does it make sense that _all_ of the text is red?

    Move the `color: red;` property up and down with <kbd>Alt</kbd> + <kbd>&uparrow;</kbd>/<kbd>&downarrow;</kbd>. When is the color property passed down from a parent element to its children?

    Add a `border` to `.inner`. How many bordered boxes do you expect to see? What would the page look like if `border` was inherited?
  runtime: repl
  mode:
    document: html
  initial:
    css: |-
      .outer {
        color: red;
      }

      .inner {
      }
      
      .inner h2{
      }

      .inner p {
      }

      .paragraph-two {
      }

      .highlighted {
      }
  solution:
    css: |-
      .outer {
      }

      .inner {
        color: red;
        border: 1px solid red;
      }
      
      .inner h2 {
        border: 1px solid red;
      }

      .inner p {
        border: 1px solid red;
      }

      .paragraph-two {
        border: 1px solid red;
      }

      .highlighted {
        border: 1px solid red;
      }
output: js4shiny::html_document_js4shiny

---
<div><!--for pandoc-->
<div class="outer">

  <h1>Lorem Title</h1>

  <div class="inner">

    <h2>Section One</h2>

    <p class="paragraph-one">
      Ipsum hendrerit natoque ultricies vitae egestas cras condimentum quis.
      <span class="highlighted">Condimentum semper cursus venenatis sodales quis magnis commodo posuere!</span>
      Nisl inceptos quis nunc arcu nostra quam eros dui posuere dictumst mus conubia ad netus!
    </p>

    <p class="paragraph-two">
      Dolor fringilla dis penatibus consequat montes in maecenas pharetra et donec.
      Nascetur purus justo rutrum ultricies sollicitudin ac bibendum phasellus cubilia vestibulum!
      Metus turpis mattis hac sodales leo laoreet.
      Nascetur erat integer volutpat sapien venenatis himenaeos ridiculus nascetur arcu pretium.
    </p>

  </div>

  <h2>Section Two</h2>

  <p class="paragraph-three">
    Sit sollicitudin fusce torquent vivamus donec scelerisque odio etiam arcu facilisi non cum velit massa!
    <span class="highlighted">Fermentum gravida integer auctor molestie quis dignissim tincidunt gravida!</span>
    Tellus quis tempor habitasse curae sem integer tellus tempor pulvinar?
    In natoque suscipit ultrices etiam ridiculus eu etiam commodo enim porta neque.
    A a quisque montes habitant tristique habitant!
  </p>
</div>
</div><!--for pandoc-->
